name: SREFormer
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.19
  - pip
  - pytorch=2.11.0
  - torchvision=0.26.0
  - pytorch-cuda=12.8
  - numpy
  - scipy
  - pyyaml
  - tqdm
  - pip:
      - SimpleITK
      - nibabel
      - einops
      - monai
      - scikit-image
      - medpy
      - thop
